LQF 4 slides fr translation to french
lunatech-labs/lunatech-beginner-quarkus-course pull request #34
Opened 2021-11-19 11:43 UTC by abensoussan

2021-11-19 13:49 UTC, mcahuet commented on slides-fr/01-introduction.md
> +Discutez avec le groupe s'ils sont intéressés par Qute ou pas du tout. Sinon, il peut être ignoré afin d'avoir plus de temps à la fin pour du contenu supplémentaire.
Discutez avec le groupe pour savoir s'ils sont intéressés par Qute ou pas du tout.

2021-11-19 13:50 UTC, mcahuet commented on slides-fr/01-introduction.md
> +TODO : Expliquez soit les Outils de Gestion de Cours, or comment utiliser Vanilla Git pours'assurer que les étudiants ne soient pas perdus.
TODO : Expliquez soit les Outils de Gestion de Cours, ou comment utiliser Vanilla Git pour s'assurer que les étudiants ne soient pas perdus.

2021-11-24 08:52 UTC, mcahuet requested changes

2021-11-24 08:52 UTC, mcahuet commented on slides-fr/03-qute.md
> +* À la dernière ligne, nous utilisons la notation infixe
```suggestion
* À la dernière ligne, nous utilisons la notation `infix`
```

2021-11-24 12:59 UTC, abensoussan commented on slides-fr/03-qute.md
> +* À la dernière ligne, nous utilisons la notation infixe
J'ai corrigé tous les retours

2021-11-24 14:09 UTC, mcahuet approved these changes

2021-12-01 14:00 UTC, merged